
DROP TABLE IF EXISTS ORGANISATION;

CREATE TABLE ORGANISATION (
  org_id INTEGER PRIMARY KEY ,
  org_name VARCHAR(50) NOT NULL,
  org_headoffice VARCHAR(50) NOT NULL,
  org_address VARCHAR(100) NOT NULL,
  created_by VARCHAR(50) NOT NULL,
  created_date TIMESTAMP NOT NULL,
  last_updated_date TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE EMPLOYEES (
  emp_id INTEGER NOT NULL ,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  email VARCHAR(50) NULL,
  passwd VARCHAR(50) NOT NULL,
  org_id INTEGER NOT NULL,
  asset_id INTEGER NOT NULL,
  created_by VARCHAR(50) NOT NULL,
  created_date TIMESTAMP NOT NULL,
  last_updated_date TIMESTAMP NOT NULL
);


DROP TABLE IF EXISTS ASSET;

CREATE TABLE ASSET (
  asset_id INTEGER NOT NULL,
  asset_type VARCHAR(50) NOT NULL,
  emp_id INTEGER NOT NULL,
  org_id INTEGER NOT NULL,
  created_by VARCHAR(50) NOT NULL,
  created_date TIMESTAMP NOT NULL,
  last_updated_date TIMESTAMP NOT NULL
);

DROP SEQUENCE IF EXISTS ORG_SEQ;

CREATE SEQUENCE "ORG_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 100;

DROP SEQUENCE IF EXISTS EMP_SEQ;

CREATE SEQUENCE "EMP_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 100;

DROP SEQUENCE IF EXISTS ASSET_SEQ;

CREATE SEQUENCE "ASSET_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 1 
START WITH 100;